'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3643
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.42.
'
Namespace EbiWS.IPRScanWs
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="JDispatcherServiceHttpBinding", [Namespace]:="http://soap.jdispatcher.ebi.ac.uk")>  _
    Partial Public Class JDispatcherService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private runOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getResultTypesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getResultOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getParametersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getParameterDetailsOperationCompleted As System.Threading.SendOrPostCallback
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://www.ebi.ac.uk/Tools/services/soap/iprscan"
        End Sub
        
        '''<remarks/>
        Public Event runCompleted As runCompletedEventHandler
        
        '''<remarks/>
        Public Event getStatusCompleted As getStatusCompletedEventHandler
        
        '''<remarks/>
        Public Event getResultTypesCompleted As getResultTypesCompletedEventHandler
        
        '''<remarks/>
        Public Event getResultCompleted As getResultCompletedEventHandler
        
        '''<remarks/>
        Public Event getParametersCompleted As getParametersCompletedEventHandler
        
        '''<remarks/>
        Public Event getParameterDetailsCompleted As getParameterDetailsCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Run", RequestNamespace:="http://soap.jdispatcher.ebi.ac.uk", ResponseNamespace:="http://soap.jdispatcher.ebi.ac.uk", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function run(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal email As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)> ByVal title As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal parameters As InputParameters) As <System.Xml.Serialization.XmlElementAttribute("jobId", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> String
            Dim results() As Object = Me.Invoke("run", New Object() {email, title, parameters})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function Beginrun(ByVal email As String, ByVal title As String, ByVal parameters As InputParameters, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("run", New Object() {email, title, parameters}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endrun(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub runAsync(ByVal email As String, ByVal title As String, ByVal parameters As InputParameters)
            Me.runAsync(email, title, parameters, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub runAsync(ByVal email As String, ByVal title As String, ByVal parameters As InputParameters, ByVal userState As Object)
            If (Me.runOperationCompleted Is Nothing) Then
                Me.runOperationCompleted = AddressOf Me.OnrunOperationCompleted
            End If
            Me.InvokeAsync("run", New Object() {email, title, parameters}, Me.runOperationCompleted, userState)
        End Sub
        
        Private Sub OnrunOperationCompleted(ByVal arg As Object)
            If (Not (Me.runCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent runCompleted(Me, New runCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetStatus", RequestNamespace:="http://soap.jdispatcher.ebi.ac.uk", ResponseNamespace:="http://soap.jdispatcher.ebi.ac.uk", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getStatus(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal jobId As String) As <System.Xml.Serialization.XmlElementAttribute("status", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> String
            Dim results() As Object = Me.Invoke("getStatus", New Object() {jobId})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BegingetStatus(ByVal jobId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getStatus", New Object() {jobId}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetStatus(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getStatusAsync(ByVal jobId As String)
            Me.getStatusAsync(jobId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getStatusAsync(ByVal jobId As String, ByVal userState As Object)
            If (Me.getStatusOperationCompleted Is Nothing) Then
                Me.getStatusOperationCompleted = AddressOf Me.OngetStatusOperationCompleted
            End If
            Me.InvokeAsync("getStatus", New Object() {jobId}, Me.getStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OngetStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.getStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getStatusCompleted(Me, New getStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetResultTypes", RequestNamespace:="http://soap.jdispatcher.ebi.ac.uk", ResponseNamespace:="http://soap.jdispatcher.ebi.ac.uk", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getResultTypes(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal jobId As String) As <System.Xml.Serialization.XmlArrayAttribute("resultTypes", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified), System.Xml.Serialization.XmlArrayItemAttribute("type", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)> wsResultType()
            Dim results() As Object = Me.Invoke("getResultTypes", New Object() {jobId})
            Return CType(results(0),wsResultType())
        End Function
        
        '''<remarks/>
        Public Function BegingetResultTypes(ByVal jobId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getResultTypes", New Object() {jobId}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetResultTypes(ByVal asyncResult As System.IAsyncResult) As wsResultType()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),wsResultType())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getResultTypesAsync(ByVal jobId As String)
            Me.getResultTypesAsync(jobId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getResultTypesAsync(ByVal jobId As String, ByVal userState As Object)
            If (Me.getResultTypesOperationCompleted Is Nothing) Then
                Me.getResultTypesOperationCompleted = AddressOf Me.OngetResultTypesOperationCompleted
            End If
            Me.InvokeAsync("getResultTypes", New Object() {jobId}, Me.getResultTypesOperationCompleted, userState)
        End Sub
        
        Private Sub OngetResultTypesOperationCompleted(ByVal arg As Object)
            If (Not (Me.getResultTypesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getResultTypesCompleted(Me, New getResultTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetResult", RequestNamespace:="http://soap.jdispatcher.ebi.ac.uk", ResponseNamespace:="http://soap.jdispatcher.ebi.ac.uk", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getResult(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal jobId As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal type As String, <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute("parameter", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)> ByVal parameters() As wsRawOutputParameter) As <System.Xml.Serialization.XmlElementAttribute("output", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)> Byte()
            Dim results() As Object = Me.Invoke("getResult", New Object() {jobId, type, parameters})
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Function BegingetResult(ByVal jobId As String, ByVal type As String, ByVal parameters() As wsRawOutputParameter, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getResult", New Object() {jobId, type, parameters}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetResult(ByVal asyncResult As System.IAsyncResult) As Byte()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Byte())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getResultAsync(ByVal jobId As String, ByVal type As String, ByVal parameters() As wsRawOutputParameter)
            Me.getResultAsync(jobId, type, parameters, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getResultAsync(ByVal jobId As String, ByVal type As String, ByVal parameters() As wsRawOutputParameter, ByVal userState As Object)
            If (Me.getResultOperationCompleted Is Nothing) Then
                Me.getResultOperationCompleted = AddressOf Me.OngetResultOperationCompleted
            End If
            Me.InvokeAsync("getResult", New Object() {jobId, type, parameters}, Me.getResultOperationCompleted, userState)
        End Sub
        
        Private Sub OngetResultOperationCompleted(ByVal arg As Object)
            If (Not (Me.getResultCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getResultCompleted(Me, New getResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetParameters", RequestNamespace:="http://soap.jdispatcher.ebi.ac.uk", ResponseNamespace:="http://soap.jdispatcher.ebi.ac.uk", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getParameters() As <System.Xml.Serialization.XmlArrayAttribute("parameters", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified), System.Xml.Serialization.XmlArrayItemAttribute("id", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)> String()
            Dim results() As Object = Me.Invoke("getParameters", New Object(-1) {})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Function BegingetParameters(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getParameters", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetParameters(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getParametersAsync()
            Me.getParametersAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getParametersAsync(ByVal userState As Object)
            If (Me.getParametersOperationCompleted Is Nothing) Then
                Me.getParametersOperationCompleted = AddressOf Me.OngetParametersOperationCompleted
            End If
            Me.InvokeAsync("getParameters", New Object(-1) {}, Me.getParametersOperationCompleted, userState)
        End Sub
        
        Private Sub OngetParametersOperationCompleted(ByVal arg As Object)
            If (Not (Me.getParametersCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getParametersCompleted(Me, New getParametersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetParameterDetails", RequestNamespace:="http://soap.jdispatcher.ebi.ac.uk", ResponseNamespace:="http://soap.jdispatcher.ebi.ac.uk", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getParameterDetails(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal parameterId As String) As <System.Xml.Serialization.XmlElementAttribute("parameterDetails", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> wsParameterDetails
            Dim results() As Object = Me.Invoke("getParameterDetails", New Object() {parameterId})
            Return CType(results(0),wsParameterDetails)
        End Function
        
        '''<remarks/>
        Public Function BegingetParameterDetails(ByVal parameterId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getParameterDetails", New Object() {parameterId}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetParameterDetails(ByVal asyncResult As System.IAsyncResult) As wsParameterDetails
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),wsParameterDetails)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getParameterDetailsAsync(ByVal parameterId As String)
            Me.getParameterDetailsAsync(parameterId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getParameterDetailsAsync(ByVal parameterId As String, ByVal userState As Object)
            If (Me.getParameterDetailsOperationCompleted Is Nothing) Then
                Me.getParameterDetailsOperationCompleted = AddressOf Me.OngetParameterDetailsOperationCompleted
            End If
            Me.InvokeAsync("getParameterDetails", New Object() {parameterId}, Me.getParameterDetailsOperationCompleted, userState)
        End Sub
        
        Private Sub OngetParameterDetailsOperationCompleted(ByVal arg As Object)
            If (Not (Me.getParameterDetailsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getParameterDetailsCompleted(Me, New getParameterDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.jdispatcher.ebi.ac.uk")>  _
    Partial Public Class InputParameters
        
        Private nocrcField As System.Nullable(Of Boolean)
        
        Private nocrcFieldSpecified As Boolean
        
        Private gotermsField As System.Nullable(Of Boolean)
        
        Private gotermsFieldSpecified As Boolean
        
        Private applField() As String
        
        Private sequenceField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property nocrc() As System.Nullable(Of Boolean)
            Get
                Return Me.nocrcField
            End Get
            Set
                Me.nocrcField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property nocrcSpecified() As Boolean
            Get
                Return Me.nocrcFieldSpecified
            End Get
            Set
                Me.nocrcFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property goterms() As System.Nullable(Of Boolean)
            Get
                Return Me.gotermsField
            End Get
            Set
                Me.gotermsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property gotermsSpecified() As Boolean
            Get
                Return Me.gotermsFieldSpecified
            End Get
            Set
                Me.gotermsFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property appl() As String()
            Get
                Return Me.applField
            End Get
            Set
                Me.applField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property sequence() As String
            Get
                Return Me.sequenceField
            End Get
            Set
                Me.sequenceField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.jdispatcher.ebi.ac.uk")>  _
    Partial Public Class wsProperty
        
        Private keyField As String
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.jdispatcher.ebi.ac.uk")>  _
    Partial Public Class wsParameterValue
        
        Private labelField As String
        
        Private valueField As String
        
        Private defaultValueField As Boolean
        
        Private propertiesField() As wsProperty
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property label() As String
            Get
                Return Me.labelField
            End Get
            Set
                Me.labelField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property defaultValue() As Boolean
            Get
                Return Me.defaultValueField
            End Get
            Set
                Me.defaultValueField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("property", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property properties() As wsProperty()
            Get
                Return Me.propertiesField
            End Get
            Set
                Me.propertiesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.jdispatcher.ebi.ac.uk")>  _
    Partial Public Class wsParameterDetails
        
        Private nameField As String
        
        Private descriptionField As String
        
        Private typeField As String
        
        Private valuesField() As wsParameterValue
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("value", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property values() As wsParameterValue()
            Get
                Return Me.valuesField
            End Get
            Set
                Me.valuesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.jdispatcher.ebi.ac.uk")>  _
    Partial Public Class wsRawOutputParameter
        
        Private nameField As String
        
        Private valueField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property value() As String()
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soap.jdispatcher.ebi.ac.uk")>  _
    Partial Public Class wsResultType
        
        Private descriptionField As String
        
        Private fileSuffixField As String
        
        Private identifierField As String
        
        Private labelField As String
        
        Private mediaTypeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fileSuffix() As String
            Get
                Return Me.fileSuffixField
            End Get
            Set
                Me.fileSuffixField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property identifier() As String
            Get
                Return Me.identifierField
            End Get
            Set
                Me.identifierField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property label() As String
            Get
                Return Me.labelField
            End Get
            Set
                Me.labelField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mediaType() As String
            Get
                Return Me.mediaTypeField
            End Get
            Set
                Me.mediaTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")>  _
    Public Delegate Sub runCompletedEventHandler(ByVal sender As Object, ByVal e As runCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class runCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")>  _
    Public Delegate Sub getStatusCompletedEventHandler(ByVal sender As Object, ByVal e As getStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")>  _
    Public Delegate Sub getResultTypesCompletedEventHandler(ByVal sender As Object, ByVal e As getResultTypesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getResultTypesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As wsResultType()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),wsResultType())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")>  _
    Public Delegate Sub getResultCompletedEventHandler(ByVal sender As Object, ByVal e As getResultCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getResultCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Byte())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")>  _
    Public Delegate Sub getParametersCompletedEventHandler(ByVal sender As Object, ByVal e As getParametersCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getParametersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")>  _
    Public Delegate Sub getParameterDetailsCompletedEventHandler(ByVal sender As Object, ByVal e As getParameterDetailsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getParameterDetailsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As wsParameterDetails
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),wsParameterDetails)
            End Get
        End Property
    End Class
End Namespace
