// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace NcbiBlastClient.EbiWS.NcbiBlast {
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBinding(Name="JDispatcherServiceHttpPort", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JDispatcherService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback runOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback getResultTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback getParametersOperationCompleted;
        
        private System.Threading.SendOrPostCallback getParameterDetailsOperationCompleted;
        
        public JDispatcherService() {
            this.Url = "http://wwwdev.ebi.ac.uk/Tools/jdispatcher/services/soap/ncbiblast";
        }
        
        public JDispatcherService(string url) {
            this.Url = url;
        }
        
        public event runCompletedEventHandler runCompleted;
        
        public event getStatusCompletedEventHandler getStatusCompleted;
        
        public event getResultTypesCompletedEventHandler getResultTypesCompleted;
        
        public event getResultCompletedEventHandler getResultCompleted;
        
        public event getParametersCompletedEventHandler getParametersCompleted;
        
        public event getParameterDetailsCompletedEventHandler getParameterDetailsCompleted;
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Run", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("runResponse", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
        public MessageRunResponse run([System.Xml.Serialization.XmlElementAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")] MessageRun run) {
            object[] results = this.Invoke("run", new object[] {
                        run});
            return ((MessageRunResponse)(results[0]));
        }
        
        public System.IAsyncResult Beginrun(MessageRun run, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("run", new object[] {
                        run}, callback, asyncState);
        }
        
        public MessageRunResponse Endrun(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageRunResponse)(results[0]));
        }
        
        public void runAsync(MessageRun run) {
            this.runAsync(run, null);
        }
        
        public void runAsync(MessageRun run, object userState) {
            if ((this.runOperationCompleted == null)) {
                this.runOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrunCompleted);
            }
            this.InvokeAsync("run", new object[] {
                        run}, this.runOperationCompleted, userState);
        }
        
        private void OnrunCompleted(object arg) {
            if ((this.runCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.runCompleted(this, new runCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetStatus", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getStatusResponse", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
        public MessageGetStatusResponse getStatus([System.Xml.Serialization.XmlElementAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")] MessageGetStatus getStatus) {
            object[] results = this.Invoke("getStatus", new object[] {
                        getStatus});
            return ((MessageGetStatusResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetStatus(MessageGetStatus getStatus, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getStatus", new object[] {
                        getStatus}, callback, asyncState);
        }
        
        public MessageGetStatusResponse EndgetStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetStatusResponse)(results[0]));
        }
        
        public void getStatusAsync(MessageGetStatus getStatus) {
            this.getStatusAsync(getStatus, null);
        }
        
        public void getStatusAsync(MessageGetStatus getStatus, object userState) {
            if ((this.getStatusOperationCompleted == null)) {
                this.getStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStatusCompleted);
            }
            this.InvokeAsync("getStatus", new object[] {
                        getStatus}, this.getStatusOperationCompleted, userState);
        }
        
        private void OngetStatusCompleted(object arg) {
            if ((this.getStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStatusCompleted(this, new getStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetResultTypes", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getResultTypesResponse", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
        public MessageGetResultTypesResponse getResultTypes([System.Xml.Serialization.XmlElementAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")] MessageGetResultTypes getResultTypes) {
            object[] results = this.Invoke("getResultTypes", new object[] {
                        getResultTypes});
            return ((MessageGetResultTypesResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetResultTypes(MessageGetResultTypes getResultTypes, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getResultTypes", new object[] {
                        getResultTypes}, callback, asyncState);
        }
        
        public MessageGetResultTypesResponse EndgetResultTypes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetResultTypesResponse)(results[0]));
        }
        
        public void getResultTypesAsync(MessageGetResultTypes getResultTypes) {
            this.getResultTypesAsync(getResultTypes, null);
        }
        
        public void getResultTypesAsync(MessageGetResultTypes getResultTypes, object userState) {
            if ((this.getResultTypesOperationCompleted == null)) {
                this.getResultTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetResultTypesCompleted);
            }
            this.InvokeAsync("getResultTypes", new object[] {
                        getResultTypes}, this.getResultTypesOperationCompleted, userState);
        }
        
        private void OngetResultTypesCompleted(object arg) {
            if ((this.getResultTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getResultTypesCompleted(this, new getResultTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetResult", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getResultResponse", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
        public MessageGetResultResponse getResult([System.Xml.Serialization.XmlElementAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")] MessageGetResult getResult) {
            object[] results = this.Invoke("getResult", new object[] {
                        getResult});
            return ((MessageGetResultResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetResult(MessageGetResult getResult, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getResult", new object[] {
                        getResult}, callback, asyncState);
        }
        
        public MessageGetResultResponse EndgetResult(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetResultResponse)(results[0]));
        }
        
        public void getResultAsync(MessageGetResult getResult) {
            this.getResultAsync(getResult, null);
        }
        
        public void getResultAsync(MessageGetResult getResult, object userState) {
            if ((this.getResultOperationCompleted == null)) {
                this.getResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetResultCompleted);
            }
            this.InvokeAsync("getResult", new object[] {
                        getResult}, this.getResultOperationCompleted, userState);
        }
        
        private void OngetResultCompleted(object arg) {
            if ((this.getResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getResultCompleted(this, new getResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetParameters", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getParametersResponse", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
        public MessageGetParametersResponse getParameters([System.Xml.Serialization.XmlElementAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")] MessageGetParameters getParameters) {
            object[] results = this.Invoke("getParameters", new object[] {
                        getParameters});
            return ((MessageGetParametersResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetParameters(MessageGetParameters getParameters, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getParameters", new object[] {
                        getParameters}, callback, asyncState);
        }
        
        public MessageGetParametersResponse EndgetParameters(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetParametersResponse)(results[0]));
        }
        
        public void getParametersAsync(MessageGetParameters getParameters) {
            this.getParametersAsync(getParameters, null);
        }
        
        public void getParametersAsync(MessageGetParameters getParameters, object userState) {
            if ((this.getParametersOperationCompleted == null)) {
                this.getParametersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetParametersCompleted);
            }
            this.InvokeAsync("getParameters", new object[] {
                        getParameters}, this.getParametersOperationCompleted, userState);
        }
        
        private void OngetParametersCompleted(object arg) {
            if ((this.getParametersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getParametersCompleted(this, new getParametersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetParameterDetails", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("getParameterDetailsResponse", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
        public MessageGetParameterDetailsResponse getParameterDetails([System.Xml.Serialization.XmlElementAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")] MessageGetParameterDetails getParameterDetails) {
            object[] results = this.Invoke("getParameterDetails", new object[] {
                        getParameterDetails});
            return ((MessageGetParameterDetailsResponse)(results[0]));
        }
        
        public System.IAsyncResult BegingetParameterDetails(MessageGetParameterDetails getParameterDetails, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getParameterDetails", new object[] {
                        getParameterDetails}, callback, asyncState);
        }
        
        public MessageGetParameterDetailsResponse EndgetParameterDetails(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MessageGetParameterDetailsResponse)(results[0]));
        }
        
        public void getParameterDetailsAsync(MessageGetParameterDetails getParameterDetails) {
            this.getParameterDetailsAsync(getParameterDetails, null);
        }
        
        public void getParameterDetailsAsync(MessageGetParameterDetails getParameterDetails, object userState) {
            if ((this.getParameterDetailsOperationCompleted == null)) {
                this.getParameterDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetParameterDetailsCompleted);
            }
            this.InvokeAsync("getParameterDetails", new object[] {
                        getParameterDetails}, this.getParameterDetailsOperationCompleted, userState);
        }
        
        private void OngetParameterDetailsCompleted(object arg) {
            if ((this.getParameterDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getParameterDetailsCompleted(this, new getParameterDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    [System.Xml.Serialization.XmlRootAttribute("run", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class MessageRun {
        
        /// <remarks/>
        public string email;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string title;
        
        /// <remarks/>
        public InputParameters parameters;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class InputParameters {
        
        /// <remarks/>
        public string program;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string matrix;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, DataType="int")]
        public System.Nullable<int> alignments;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool alignmentsSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, DataType="int")]
        public System.Nullable<int> scores;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool scoresSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string exp;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, DataType="int")]
        public System.Nullable<int> dropoff;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool dropoffSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string match_scores;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, DataType="int")]
        public System.Nullable<int> gapopen;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool gapopenSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, DataType="int")]
        public System.Nullable<int> gapext;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool gapextSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string filter;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string seqrange;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, DataType="boolean")]
        public System.Nullable<bool> gapalign;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool gapalignSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, DataType="int")]
        public System.Nullable<int> align;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnore()]
        public bool alignSpecified;
        
        /// <remarks/>
        public string stype;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sequence;
        
        /// <remarks/>
        public string[] database;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    [System.Xml.Serialization.XmlRootAttribute("runResponse", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class MessageRunResponse {
        
        /// <remarks/>
        public string jobId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    [System.Xml.Serialization.XmlRootAttribute("getStatus", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class MessageGetStatus {
        
        /// <remarks/>
        public string jobId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    [System.Xml.Serialization.XmlRootAttribute("getStatusResponse", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class MessageGetStatusResponse {
        
        /// <remarks/>
        public string status;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    [System.Xml.Serialization.XmlRootAttribute("getResultTypes", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class MessageGetResultTypes {
        
        /// <remarks/>
        public string jobId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    [System.Xml.Serialization.XmlRootAttribute("getResultTypesResponse", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class MessageGetResultTypesResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="type", IsNullable=false)]
        public wsResultType[] resultTypes;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class wsResultType {
        
        /// <remarks/>
        public string identifier;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string label;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string description;
        
        /// <remarks/>
        public string mediaType;
        
        /// <remarks/>
        public string fileSuffix;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    [System.Xml.Serialization.XmlRootAttribute("getResult", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class MessageGetResult {
        
        /// <remarks/>
        public string jobId;
        
        /// <remarks/>
        public string type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArray(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItem(ElementName="parameter", IsNullable=false)]
        public wsRawOutputParameter[] parameters;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class wsRawOutputParameter {
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public string[] value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    [System.Xml.Serialization.XmlRootAttribute("getResultResponse", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class MessageGetResultResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public byte[] output;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    [System.Xml.Serialization.XmlRootAttribute("getParameters", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class MessageGetParameters {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    [System.Xml.Serialization.XmlRootAttribute("getParametersResponse", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class MessageGetParametersResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="id", IsNullable=false)]
        public string[] parameters;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    [System.Xml.Serialization.XmlRootAttribute("getParameterDetails", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class MessageGetParameterDetails {
        
        /// <remarks/>
        public string parameterId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    [System.Xml.Serialization.XmlRootAttribute("getParameterDetailsResponse", Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class MessageGetParameterDetailsResponse {
        
        /// <remarks/>
        public wsParameterDetails parameterDetails;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class wsParameterDetails {
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        public string description;
        
        /// <remarks/>
        public string type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="value", IsNullable=false)]
        public wsParameterValue[] values;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class wsParameterValue {
        
        /// <remarks/>
        public string label;
        
        /// <remarks/>
        public string value;
        
        /// <remarks/>
        public bool defaultValue;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="property", IsNullable=false)]
        public wsProperty[] properties;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.jdispatcher.ebi.ac.uk")]
    public partial class wsProperty {
        
        /// <remarks/>
        public string key;
        
        /// <remarks/>
        public string value;
    }
    
    public partial class runCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal runCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageRunResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageRunResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void runCompletedEventHandler(object sender, runCompletedEventArgs args);
    
    public partial class getStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetStatusResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetStatusResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getStatusCompletedEventHandler(object sender, getStatusCompletedEventArgs args);
    
    public partial class getResultTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getResultTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetResultTypesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetResultTypesResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getResultTypesCompletedEventHandler(object sender, getResultTypesCompletedEventArgs args);
    
    public partial class getResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetResultResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetResultResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getResultCompletedEventHandler(object sender, getResultCompletedEventArgs args);
    
    public partial class getParametersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getParametersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetParametersResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetParametersResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getParametersCompletedEventHandler(object sender, getParametersCompletedEventArgs args);
    
    public partial class getParameterDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getParameterDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MessageGetParameterDetailsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessageGetParameterDetailsResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void getParameterDetailsCompletedEventHandler(object sender, getParameterDetailsCompletedEventArgs args);
}
