# $Id$
# ======================================================================
#
# Makefile to build VB.NET EB-eye client using Mono.
#
# ======================================================================

# VB.NET compiler
VBC = vbnc
# VB.NET compiler flags
VBFLAGS = 

# Directory for compiled binaries
BINDIR = bin
DEBUGBINDIR = $(BINDIR)/Debug
RELEASEBINDIR = $(BINDIR)/Release

# Core assembly project
EBIWS = ../EbiWS

all: EBeyeCliClient

### FASTA command-line client ###

EBeyeCliClient: $(DEBUGBINDIR)/EBeyeCliClient.exe $(RELEASEBINDIR)/EBeyeCliClient.exe

$(DEBUGBINDIR)/EBeyeCliClient.exe: EBeyeCliClient.vb $(DEBUGBINDIR)/EbiWS.dll
	mkdir -p $(DEBUGBINDIR)
	$(VBC) $(VBFLAGS) -debug -target:exe -reference:$(DEBUGBINDIR)/EbiWS.dll -out:$@ EBeyeCliClient.vb

$(DEBUGBINDIR)/EbiWS.dll: $(EBIWS)/$(DEBUGBINDIR)/EbiWS.dll
	mkdir -p $(DEBUGBINDIR)
	cp $(EBIWS)/$(DEBUGBINDIR)/EbiWS.dll* $(DEBUGBINDIR)/

$(RELEASEBINDIR)/EBeyeCliClient.exe: EBeyeCliClient.vb $(RELEASEBINDIR)/EbiWS.dll
	mkdir -p $(RELEASEBINDIR)
	$(VBC) $(VBFLAGS) -target:exe -reference:$(RELEASEBINDIR)/EbiWS.dll -out:$@ EBeyeCliClient.vb

$(RELEASEBINDIR)/EbiWS.dll: $(EBIWS)/$(RELEASEBINDIR)/EbiWS.dll
	mkdir -p $(RELEASEBINDIR)
	cp $(EBIWS)/$(RELEASEBINDIR)/EbiWS.dll* $(RELEASEBINDIR)/

clean:
	find . -name '*~' -exec rm {} \;

distclean: clean
	rm -rf $(DEBUGBINDIR) $(RELEASEBINDIR) bin/
