# $Id$
# ======================================================================
#
# Makefile to build C# MAFFT client using MS .NET SDK.
#
# ======================================================================

# C# compiler
CSC = csc
# C# compiler flags
CSFLAGS = 

# Directory for compiled binaries
BINDIR = bin
DEBUGBINDIR = $(BINDIR)\Debug
RELEASEBINDIR = $(BINDIR)\Release

# Core assembly project
EBIWS = ..\EbiWS

all: MafftCliClient

$(BINDIR):
	mkdir $(BINDIR)

$(DEBUGBINDIR): $(BINDIR)
	mkdir $(DEBUGBINDIR)

$(RELEASEBINDIR): $(BINDIR)
	mkdir $(RELEASEBINDIR)

### MAFFT command-line client ###

MafftCliClient: $(DEBUGBINDIR)\MafftCliClient.exe $(RELEASEBINDIR)\MafftCliClient.exe

$(DEBUGBINDIR)\MafftCliClient.exe: $(DEBUGBINDIR) MafftCliClient.cs $(DEBUGBINDIR)\EbiWS.dll
	$(CSC) $(CSFLAGS) /debug /target:exe /reference:$(DEBUGBINDIR)\EbiWS.dll /out:$@ MafftCliClient.cs

$(DEBUGBINDIR)\EbiWS.dll: $(DEBUGBINDIR) $(EBIWS)\$(DEBUGBINDIR)\EbiWS.dll
	copy $(EBIWS)\$(DEBUGBINDIR)\EbiWS.dll* $(DEBUGBINDIR)

$(RELEASEBINDIR)\MafftCliClient.exe: $(RELEASEBINDIR) MafftCliClient.cs $(RELEASEBINDIR)\EbiWS.dll
	$(CSC) $(CSFLAGS) /target:exe /reference:$(RELEASEBINDIR)\EbiWS.dll /out:$@ MafftCliClient.cs

$(RELEASEBINDIR)\EbiWS.dll: $(RELEASEBINDIR) $(EBIWS)\$(RELEASEBINDIR)\EbiWS.dll
	copy $(EBIWS)\$(RELEASEBINDIR)\EbiWS.dll* $(RELEASEBINDIR)

clean:

distclean: clean
	del /Q /f $(DEBUGBINDIR)\*.* $(RELEASEBINDIR)\*.*
	rmdir $(DEBUGBINDIR)
	rmdir $(RELEASEBINDIR)
	rmdir $(BINDIR)
