# $Id$
# ======================================================================
#
# Makefile to build C# EBI Web Services clients using Mono.
#
# ======================================================================

# C# compiler
CSC = gmcs
# C# compiler flags
CSFLAGS = -r:System.Web.Services

# WSDL to C# tool
WSDL2CS = wsdl2
# WSDL to C# flags
WSDL2CSFLAGS = -namespace:EbiWS

# Directory for compiled binaries
BINDIR = bin
DEBUGBINDIR = $(BINDIR)/Debug
RELEASEBINDIR = $(BINDIR)/Release
# Directory for generated stubs code
STUBSRCDIR = WebReferences

# Base URL of Tool WSDLs
WSDLBASE = http://www.ebi.ac.uk/Tools/services/soap

all: EbiWS

### EbiWS ###

EbiWS: EbiWS.dll

EbiWS.dll: $(DEBUGBINDIR)/EbiWS.dll $(RELEASEBINDIR)/EbiWS.dll

EbiWS.netmodule: $(DEBUGBINDIR)/EbiWS.netmodule $(RELEASEBINDIR)/EbiWS.netmodule

coreSrc = AbstractWsClient.cs \
EBeyeClient.cs \
FastaClient.cs \
NcbiBlastClient.cs \
WuBlastClient.cs

stubSrc = \
$(STUBSRCDIR)/EBeyeWs/Reference.cs \
$(STUBSRCDIR)/FastaWs/Reference.cs \
$(STUBSRCDIR)/NcbiBlastWs/Reference.cs \
$(STUBSRCDIR)/WuBlastWs/Reference.cs

$(DEBUGBINDIR)/EbiWS.dll: $(coreSrc) $(stubSrc)
	mkdir -p $(DEBUGBINDIR)
	$(CSC) $(CSFLAGS) -debug -target:library -out:$@ $(coreSrc) $(stubSrc)

$(RELEASEBINDIR)/EbiWS.dll: $(coreSrc) $(stubSrc)
	mkdir -p $(RELEASEBINDIR)
	$(CSC) $(CSFLAGS) -target:library -out:$@ $(coreSrc) $(stubSrc)

$(DEBUGBINDIR)/EbiWS.netmodule: $(coreSrc) $(stubSrc)
	mkdir -p $(DEBUGBINDIR)
	$(CSC) $(CSFLAGS) -debug -target:module -out:$@ $(coreSrc) $(stubSrc)

$(RELEASEBINDIR)/EbiWS.netmodule: $(coreSrc) $(stubSrc)
	mkdir -p $(RELEASEBINDIR)
	$(CSC) $(CSFLAGS) -target:module -out:$@ $(coreSrc) $(stubSrc)

$(STUBSRCDIR)/EBeyeWs/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).EBeyeWs -out:$@ "http://www.ebi.ac.uk/ebisearch/service.ebi?wsdl"

$(STUBSRCDIR)/FastaWs/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).FastaWs -out:$@ "$(WSDLBASE)/fasta?wsdl"

$(STUBSRCDIR)/NcbiBlastWs/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).NcbiBlastWs -out:$@ "$(WSDLBASE)/ncbiblast?wsdl"
$(STUBSRCDIR)/WuBlastWs/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).WuBlastWs -out:$@ "$(WSDLBASE)/wublast?wsdl"

clean:
	find . -name '*~' -exec rm {} \;

distclean: clean
	rm -rf $(DEBUGBINDIR) $(RELEASEBINDIR) bin/

clean-stubs:
	rm -rf $(STUBSRCDIR)/*
