# $Id$
# ======================================================================
#
# Makefile to build C# EBI Web Services client library using MS .NET SDK.
#
# ======================================================================

# C# compiler
CSC = csc
# C# compiler flags
CSFLAGS = 

# WSDL to C# tool
WSDL2CS = wsdl
# WSDL to C# flags
WSDL2CSFLAGS = /namespace:EbiWS

# Directory for compiled binaries
BINDIR = bin
DEBUGBINDIR = $(BINDIR)\Debug
RELEASEBINDIR = $(BINDIR)\Release
# Directory for generated stubs code
STUBSRCDIR = WebReferences

# Base URL of Tool WSDLs
WSDLBASE = http://www.ebi.ac.uk/Tools/services/soap

all: EbiWS

$(BINDIR):
	mkdir $(BINDIR)

$(DEBUGBINDIR): $(BINDIR)
	mkdir $(DEBUGBINDIR)

$(RELEASEBINDIR): $(BINDIR)
	mkdir $(RELEASEBINDIR)

### EbiWS ###

EbiWS: $(DEBUGBINDIR)\EbiWS.dll $(RELEASEBINDIR)\EbiWS.dll

coreSrc = AbstractWsClient.cs \
ClustalOClient.cs \
ClustalW2Client.cs \
ClustalW2PhylogenyClient.cs \
DaliliteClient.cs \
DbClustalClient.cs \
EBeyeClient.cs \
EmbossMatcherClient.cs \
EmbossNeedleClient.cs \
EmbossPepinfoClient.cs \
EmbossPepstatsClient.cs \
EmbossPepwindowClient.cs \
EmbossStretcherClient.cs \
EmbossTranseqClient.cs \
EmbossSixpackClient.cs \
EmbossBacktranseqClient.cs \
EmbossBacktranambigClient.cs \
EmbossWaterClient.cs \
FastaClient.cs \
FastmClient.cs \
IPRScanClient.cs \
KalignClient.cs \
LalignClient.cs \
MafftClient.cs \
MaxsproutClient.cs \
MuscleClient.cs \
MViewClient.cs \
NcbiBlastClient.cs \
PhobiusClient.cs \
PsiBlastClient.cs \
PsiSearchClient.cs \
RadarClient.cs \
SapsClient.cs \
TcoffeeClient.cs \
WSDbfetchClient.cs \
WuBlastClient.cs

stubSrc = \
$(STUBSRCDIR)\ClustalOWs\Reference.cs \
$(STUBSRCDIR)\ClustalW2PhylogenyWs\Reference.cs \
$(STUBSRCDIR)\ClustalW2Ws\Reference.cs \
$(STUBSRCDIR)\DbClustalWs\Reference.cs \
$(STUBSRCDIR)\EBeyeWs\Reference.cs \
$(STUBSRCDIR)\FastaWs\Reference.cs \
$(STUBSRCDIR)\FastmWs\Reference.cs \
$(STUBSRCDIR)\EmbossMatcherWs\Reference.cs \
$(STUBSRCDIR)\EmbossNeedleWs\Reference.cs \
$(STUBSRCDIR)\EmbossStretcherWs\Reference.cs \
$(STUBSRCDIR)\EmbossTranseqWs\Reference.cs \
$(STUBSRCDIR)\EmbossSixpackWs\Reference.cs \
$(STUBSRCDIR)\EmbossBacktranseqWs\Reference.cs \
$(STUBSRCDIR)\EmbossBacktranambigWs\Reference.cs \
$(STUBSRCDIR)\EmbossPepinfoWs\Reference.cs \
$(STUBSRCDIR)\EmbossPepstatsWs\Reference.cs \
$(STUBSRCDIR)\EmbossPepwindowWs\Reference.cs \
$(STUBSRCDIR)\EmbossWaterWs\Reference.cs \
$(STUBSRCDIR)\IPRScanWs\Reference.cs \
$(STUBSRCDIR)\KalignWs\Reference.cs \
$(STUBSRCDIR)\LalignWs\Reference.cs \
$(STUBSRCDIR)\MafftWs\Reference.cs \
$(STUBSRCDIR)\MaxproutWs\Reference.cs \
$(STUBSRCDIR)\MuscleWs\Reference.cs \
$(STUBSRCDIR)\MViewWs\Reference.cs \
$(STUBSRCDIR)\NcbiBlastWs\Reference.cs \
$(STUBSRCDIR)\PhobiusWs\Reference.cs \
$(STUBSRCDIR)\PrankWs\Reference.cs \
$(STUBSRCDIR)\PsiBlastWs\Reference.cs \
$(STUBSRCDIR)\PsiSearchWs\Reference.cs \
$(STUBSRCDIR)\RadarWs\Reference.cs \
$(STUBSRCDIR)\SapsWs\Reference.cs \
$(STUBSRCDIR)\TcoffeeWs\Reference.cs \
$(STUBSRCDIR)\WSDbfetchWs\Reference.cs \
$(STUBSRCDIR)\WuBlastWs\Reference.cs

### Build library ###

$(DEBUGBINDIR)\EbiWS.dll: $(DEBUGBINDIR) $(coreSrc) $(stubSrc)
	$(CSC) $(CSFLAGS) /debug /target:library /out:$@ $(coreSrc) $(stubSrc)

$(RELEASEBINDIR)\EbiWS.dll: $(RELEASEBINDIR) $(coreSrc) $(stubSrc)
	$(CSC) $(CSFLAGS) /target:library /out:$@ $(coreSrc) $(stubSrc)

### Generate web service stubs ###

# Collation target to generate stubs, but not compile.
stubs: $(stubSrc)

$(STUBSRCDIR)\ClustalOWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).ClustalOWs /out:$@ "$(WSDLBASE)/clustalo?wsdl"

$(STUBSRCDIR)\ClustalW2PhylogenyWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).ClustalW2PhylogenyWs /out:$@ "$(WSDLBASE)/clustalw2_phylogeny?wsdl"

$(STUBSRCDIR)\ClustalW2Ws\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).ClustalW2Ws /out:$@ "$(WSDLBASE)/clustalw2?wsdl"

$(STUBSRCDIR)\DaliliteWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).DaliliteWs /out:$@ "$(WSDLBASE)/dalilite?wsdl"

$(STUBSRCDIR)\DbClustalWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).DbClustalWs /out:$@ "$(WSDLBASE)/dbclustal?wsdl"

$(STUBSRCDIR)\EBeyeWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).EBeyeWs /out:$@ "http://www.ebi.ac.uk/ebisearch/service.ebi?wsdl"

$(STUBSRCDIR)\FastaWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).FastaWs /out:$@ "$(WSDLBASE)/fasta?wsdl"

$(STUBSRCDIR)\FastmWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).FastmWs /out:$@ "$(WSDLBASE)/fastm?wsdl"

$(STUBSRCDIR)\EmbossMatcherWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).EmbossMatcherWs /out:$@ "$(WSDLBASE)/emboss_matcher?wsdl"

$(STUBSRCDIR)\EmbossNeedleWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).EmbossNeedleWs /out:$@ "$(WSDLBASE)/emboss_needle?wsdl"

$(STUBSRCDIR)\EmbossStretcherWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).EmbossStretcherWs /out:$@ "$(WSDLBASE)/emboss_stretcher?wsdl"

$(STUBSRCDIR)\EmbossTranseqWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).EmbossTranseqWs /out:$@ "$(WSDLBASE)/emboss_transeq?wsdl"

$(STUBSRCDIR)\EmbossSixpackWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).EmbossSixpackWs /out:$@ "$(WSDLBASE)/emboss_sixpack?wsdl"

$(STUBSRCDIR)\EmbossBacktranseqWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).EmbossBacktranseqWs /out:$@ "$(WSDLBASE)/emboss_backtranseq?wsdl"
	
$(STUBSRCDIR)\EmbossBacktranambigWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).EmbossBacktranambigWs /out:$@ "$(WSDLBASE)/emboss_backtranambig?wsdl"

$(STUBSRCDIR)\EmbossPepinfoWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).EmbossPepinfoWs /out:$@ "$(WSDLBASE)/emboss_pepinfo?wsdl"

$(STUBSRCDIR)\EmbossPepstatsWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).EmbossPepstatsWs /out:$@ "http://wwwdev.ebi.ac.uk/Tools/services/soap/emboss_pepstats?wsdl"

$(STUBSRCDIR)\EmbossPepwindowWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).EmbossPepwindowWs /out:$@ "$(WSDLBASE)/emboss_pepwindow?wsdl"

$(STUBSRCDIR)\EmbossWaterWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).EmbossWaterWs /out:$@ "$(WSDLBASE)/emboss_water?wsdl"

$(STUBSRCDIR)\IPRScanWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).IPRScanWs /out:$@ "$(WSDLBASE)/iprscan?wsdl"

$(STUBSRCDIR)\KalignWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).KalignWs /out:$@ "$(WSDLBASE)/kalign?wsdl"

$(STUBSRCDIR)\LalignWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).LalignWs /out:$@ "$(WSDLBASE)/lalign?wsdl"

$(STUBSRCDIR)\MafftWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).MafftWs /out:$@ "$(WSDLBASE)/mafft?wsdl"

$(STUBSRCDIR)\MaxsproutWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).MaxsproutWs /out:$@ "$(WSDLBASE)/maxsprout?wsdl"

$(STUBSRCDIR)\MuscleWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).MuscleWs /out:$@ "$(WSDLBASE)/muscle?wsdl"

$(STUBSRCDIR)\MViewWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).MViewWs /out:$@ "$(WSDLBASE)/mview?wsdl"

$(STUBSRCDIR)\NcbiBlastWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).NcbiBlastWs /out:$@ "$(WSDLBASE)/ncbiblast?wsdl"

$(STUBSRCDIR)\PhobiusWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).PhobiusWs /out:$@ "$(WSDLBASE)/phobius?wsdl"

$(STUBSRCDIR)\PrankWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).PrankWs /out:$@ "$(WSDLBASE)/prank?wsdl"

$(STUBSRCDIR)\PsiBlastWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).PsiBlastWs /out:$@ "$(WSDLBASE)/psiblast?wsdl"

$(STUBSRCDIR)\PsiSearchWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).PsiSearchWs /out:$@ "$(WSDLBASE)/psisearch?wsdl"

$(STUBSRCDIR)\RadarWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).RadarWs /out:$@ "$(WSDLBASE)/radar?wsdl"

$(STUBSRCDIR)\SapsWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).SapsWs /out:$@ "http://wwwdev.ebi.ac.uk/Tools/services/soap/saps?wsdl"

$(STUBSRCDIR)\TcoffeeWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).TcoffeeWs /out:$@ "$(WSDLBASE)/tcoffee?wsdl"

$(STUBSRCDIR)\WSDbfetchWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).WSDbfetchWs /out:$@ "http://www.ebi.ac.uk/ws/services/WSDbfetchDoclit?sawsdl"

$(STUBSRCDIR)\WuBlastWs\Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).WuBlastWs /out:$@ "$(WSDLBASE)/wublast?wsdl"

### Clean-up ###

clean:

distclean: clean
	del /f $(DEBUGBINDIR)\*.* $(RELEASEBINDIR)\*.*
	rmdir $(DEBUGBINDIR)
	rmdir $(RELEASEBINDIR)
	rmdir $(BINDIR)

clean-stubs:
	cd $(STUBSRCDIR)
	del /f /s *.cs
	del /f /s *.map
