# $Id$
# ======================================================================
#
# Makefile to build C# EBI Web Services clients using Mono.
#
# ======================================================================

# C# compiler
CSC = gmcs
# C# compiler flags
CSFLAGS = -r:System.Web.Services

# WSDL to C# tool
WSDL2CS = wsdl2
# WSDL to C# flags
WSDL2CSFLAGS = -namespace:EbiWS

# Directory for compiled binaries
BINDIR = bin
DEBUGBINDIR = $(BINDIR)/Debug
RELEASEBINDIR = $(BINDIR)/Release
# Directory for generated stubs code
STUBSRCDIR = WebReferences

# Base URL of Tool WSDLs
WSDLBASE = http://www.ebi.ac.uk/Tools/services/soap

all: EbiWS

### EbiWS ###

EbiWS: EbiWS.dll

EbiWS.dll: $(DEBUGBINDIR)/EbiWS.dll $(RELEASEBINDIR)/EbiWS.dll

EbiWS.netmodule: $(DEBUGBINDIR)/EbiWS.netmodule $(RELEASEBINDIR)/EbiWS.netmodule

coreSrc = AbstractWsClient.cs \
ClustalW2Client.cs \
EBeyeClient.cs \
FastaClient.cs \
FastmClient.cs \
KalignClient.cs \
MafftClient.cs \
MuscleClient.cs \
NcbiBlastClient.cs \
PsiBlastClient.cs \
PsiSearchClient.cs \
TcoffeeClient.cs \
WSDbfetchClient.cs \
WuBlastClient.cs

stubSrc = \
$(STUBSRCDIR)/ClustalW2Ws/Reference.cs \
$(STUBSRCDIR)/EBeyeWs/Reference.cs \
$(STUBSRCDIR)/FastaWs/Reference.cs \
$(STUBSRCDIR)/FastmWs/Reference.cs \
$(STUBSRCDIR)/KalignWs/Reference.cs \
$(STUBSRCDIR)/MafftWs/Reference.cs \
$(STUBSRCDIR)/MuscleWs/Reference.cs \
$(STUBSRCDIR)/NcbiBlastWs/Reference.cs \
$(STUBSRCDIR)/PsiBlastWs/Reference.cs \
$(STUBSRCDIR)/PsiSearchWs/Reference.cs \
$(STUBSRCDIR)/TcoffeeWs/Reference.cs \
$(STUBSRCDIR)/WSDbfetchWs/Reference.cs \
$(STUBSRCDIR)/WuBlastWs/Reference.cs

$(DEBUGBINDIR)/EbiWS.dll: $(coreSrc) $(stubSrc)
	mkdir -p $(DEBUGBINDIR)
	$(CSC) $(CSFLAGS) -debug -target:library -out:$@ $(coreSrc) $(stubSrc)

$(RELEASEBINDIR)/EbiWS.dll: $(coreSrc) $(stubSrc)
	mkdir -p $(RELEASEBINDIR)
	$(CSC) $(CSFLAGS) -target:library -out:$@ $(coreSrc) $(stubSrc)

$(DEBUGBINDIR)/EbiWS.netmodule: $(coreSrc) $(stubSrc)
	mkdir -p $(DEBUGBINDIR)
	$(CSC) $(CSFLAGS) -debug -target:module -out:$@ $(coreSrc) $(stubSrc)

$(RELEASEBINDIR)/EbiWS.netmodule: $(coreSrc) $(stubSrc)
	mkdir -p $(RELEASEBINDIR)
	$(CSC) $(CSFLAGS) -target:module -out:$@ $(coreSrc) $(stubSrc)

$(STUBSRCDIR)/ClustalW2Ws/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).ClustalW2Ws -out:$@ "$(WSDLBASE)/clustalw2?wsdl"

$(STUBSRCDIR)/EBeyeWs/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).EBeyeWs -out:$@ "http://www.ebi.ac.uk/ebisearch/service.ebi?wsdl"

$(STUBSRCDIR)/FastaWs/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).FastaWs -out:$@ "$(WSDLBASE)/fasta?wsdl"

$(STUBSRCDIR)/FastmWs/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).FastmWs -out:$@ "$(WSDLBASE)/fastm?wsdl"

$(STUBSRCDIR)/KalignWs/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).KalignWs -out:$@ "$(WSDLBASE)/kalign?wsdl"

$(STUBSRCDIR)/MafftWs/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).MafftWs -out:$@ "$(WSDLBASE)/mafft?wsdl"

$(STUBSRCDIR)/MuscleWs/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).MuscleWs -out:$@ "$(WSDLBASE)/muscle?wsdl"

$(STUBSRCDIR)/NcbiBlastWs/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).NcbiBlastWs -out:$@ "$(WSDLBASE)/ncbiblast?wsdl"

$(STUBSRCDIR)/PsiBlastWs/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).PsiBlastWs -out:$@ "$(WSDLBASE)/psiblast?wsdl"

$(STUBSRCDIR)/PsiSearchWs/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).PsiSearchWs -out:$@ "$(WSDLBASE)/psisearch?wsdl"

$(STUBSRCDIR)/TcoffeeWs/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).TcoffeeWs -out:$@ "$(WSDLBASE)/tcoffee?wsdl"

$(STUBSRCDIR)/WSDbfetchWs/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).WSDbfetchWs -out:$@ "http://www.ebi.ac.uk/ws/services/WSDbfetchDoclit?wsdl"

$(STUBSRCDIR)/WuBlastWs/Reference.cs:
	$(WSDL2CS) $(WSDL2CSFLAGS).WuBlastWs -out:$@ "$(WSDLBASE)/wublast?wsdl"

clean:
	find . -name '*~' -exec rm {} \;

distclean: clean
	rm -rf $(DEBUGBINDIR) $(RELEASEBINDIR) bin/

clean-stubs:
	rm -rf $(STUBSRCDIR)/*/*.cs
