# $Id$
# ======================================================================
#
# Makefile to build C# EB-eye client using MS .NET SDK.
#
# ======================================================================

# C# compiler
CSC = csc
# C# compiler flags
CSFLAGS = 

# Directory for compiled binaries
BINDIR = bin
DEBUGBINDIR = $(BINDIR)\Debug
RELEASEBINDIR = $(BINDIR)\Release

# Core assembly project
EBIWS = ..\EbiWS

all: EBeyeCliClient

$(BINDIR):
	mkdir $(BINDIR)

$(DEBUGBINDIR): $(BINDIR)
	mkdir $(DEBUGBINDIR)

$(RELEASEBINDIR): $(BINDIR)
	mkdir $(RELEASEBINDIR)

### FASTA command-line client ###

EBeyeCliClient: $(DEBUGBINDIR)\EBeyeCliClient.exe $(RELEASEBINDIR)\EBeyeCliClient.exe

$(DEBUGBINDIR)\EBeyeCliClient.exe: $(DEBUGBINDIR) EBeyeCliClient.cs $(DEBUGBINDIR)\EbiWS.dll
	$(CSC) $(CSFLAGS) /debug /target:exe /reference:$(DEBUGBINDIR)\EbiWS.dll /out:$@ EBeyeCliClient.cs

$(DEBUGBINDIR)\EbiWS.dll: $(DEBUGBINDIR) $(EBIWS)\$(DEBUGBINDIR)\EbiWS.dll
	copy $(EBIWS)\$(DEBUGBINDIR)\EbiWS.dll* $(DEBUGBINDIR)

$(RELEASEBINDIR)\EBeyeCliClient.exe: $(RELEASEBINDIR) EBeyeCliClient.cs $(RELEASEBINDIR)\EbiWS.dll
	$(CSC) $(CSFLAGS) /target:exe /reference:$(RELEASEBINDIR)\EbiWS.dll /out:$@ EBeyeCliClient.cs

$(RELEASEBINDIR)\EbiWS.dll: $(RELEASEBINDIR) $(EBIWS)\$(RELEASEBINDIR)\EbiWS.dll
	copy $(EBIWS)\$(RELEASEBINDIR)\EbiWS.dll* $(RELEASEBINDIR)

clean:

distclean: clean
	del /f $(DEBUGBINDIR)\*.* $(RELEASEBINDIR)\*.*
	rmdir $(DEBUGBINDIR)
	rmdir $(RELEASEBINDIR)
	rmdir $(BINDIR)
