
# ======================================================================
#
# Makefile to build VB.NET NCBI BLAST client using MS .NET SDK.
#
# ======================================================================

# VB.NET compiler
VBC = vbc
# VB.NET compiler flags
VBFLAGS = 

# Directory for compiled binaries
BINDIR = bin
DEBUGBINDIR = $(BINDIR)\Debug
RELEASEBINDIR = $(BINDIR)\Release

# Core assembly project
EBIWS = ..\EbiWS

all: NcbiBlastCliClient

$(BINDIR):
	mkdir $(BINDIR)

$(DEBUGBINDIR): $(BINDIR)
	mkdir $(DEBUGBINDIR)

$(RELEASEBINDIR): $(BINDIR)
	mkdir $(RELEASEBINDIR)

### NCBI BLAST command-line client ###

NcbiBlastCliClient: $(DEBUGBINDIR)\NcbiBlastCliClient.exe $(RELEASEBINDIR)\NcbiBlastCliClient.exe

$(DEBUGBINDIR)\NcbiBlastCliClient.exe: $(DEBUGBINDIR) NcbiBlastCliClient.vb $(DEBUGBINDIR)\EbiWS.dll
	$(VBC) $(VBFLAGS) /debug /target:exe /reference:$(DEBUGBINDIR)\EbiWS.dll /out:$@ NcbiBlastCliClient.vb

$(DEBUGBINDIR)\EbiWS.dll: $(DEBUGBINDIR) $(EBIWS)\$(DEBUGBINDIR)\EbiWS.dll
	copy $(EBIWS)\$(DEBUGBINDIR)\EbiWS.dll* $(DEBUGBINDIR)

$(RELEASEBINDIR)\NcbiBlastCliClient.exe: $(RELEASEBINDIR) NcbiBlastCliClient.vb $(RELEASEBINDIR)\EbiWS.dll
	$(VBC) $(VBFLAGS) /target:exe /reference:$(RELEASEBINDIR)\EbiWS.dll /out:$@ NcbiBlastCliClient.vb

$(RELEASEBINDIR)\EbiWS.dll: $(RELEASEBINDIR) $(EBIWS)\$(RELEASEBINDIR)\EbiWS.dll
	copy $(EBIWS)\$(RELEASEBINDIR)\EbiWS.dll* $(RELEASEBINDIR)

clean:

distclean: clean
	del /f $(DEBUGBINDIR)\*.* $(RELEASEBINDIR)\*.*
	rmdir $(DEBUGBINDIR)
	rmdir $(RELEASEBINDIR)
	rmdir $(BINDIR)
